In [2]:
import pandas as pd
# import numpy as np
import os
import sys

dir_path = '/home/pamya/Python/ML_Projects/Pride-of-Sahyadri'
sys.path.append(dir_path)
os.chdir(dir_path)

In [3]:
df = pd.read_csv('data/maharashtra-forts.csv')
df.sample(3)

,fort_id,name,alternate_names,district,taluka,latitude,longitude,base_village,type,elevation_m,...,built_by,year_of_construction,key_events,trek_difficulty,trek_time_hours,best_season,water_availability,accommodation,asi_protected,notes
29,30,Bahula Fort,NaN,Nashik,Nashik,19.8459,73.8741,Bahula,Giri Durg (Hill Fort),1073,...,Unknown,c. 12th Century,Watchtower fort in the Trimbak range,Easy,1.5,Winter,NaN,NaN,FALSE,A lesser-known fort offering solitude and view...
92,93,Gambhirgad,NaN,Palghar,Dahanu,20.0678,73.1165,Patilpada,Giri Durg (Hill Fort),670,...,Unknown,c. 17th Century,Guarded the northern Konkan region,Medium,2.5,Winter,Seasonal,Caves,FALSE,Known for its dense forest trek and panoramic ...
238,239,Parola Fort,NaN,Jalgaon,Parola,20.8833,75.1167,Parola,Bhuikot (Land Fort),260,...,Jahagirdar Hari Sadashiv Damodar,c. 1727,A large land fort built by the Newalkar family,Easy,0.5,Winter,NaN,NaN,FALSE,"A significant landmark in Parola town, though ..."

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fort_id               346 non-null    int64
 1   name                  346 non-null    object
 2   alternate_names       101 non-null    object
 3   district              346 non-null    object
 4   taluka                346 non-null    object
 5   latitude              346 non-null    float64
 6   longitude             346 non-null    float64
 7   base_village          346 non-null    object
 8   type                  346 non-null    object
 9   elevation_m           346 non-null    int64
 10  current_condition     346 non-null    object
 11  era                   346 non-null    object
 12  built_by              346 non-null    object
 13  year_of_construction  346 non-null    object
 14  key_events            346 non-null    object
 15  trek_difficulty       346 non-null    object
 16  trek_time_hours       346 non-null    object
 17  best_season           345 non-null    object
 18  water_availability    161 non-null    object
 19  accommodation         141 non-null    object
 20  asi_protected         346 non-null    object
 21  notes                 345 non-null    object
dtypes: float64(2), int64(2), object(18)
memory usage: 59.6+ KB

In [12]:
def fort_dict_to_paragraph(data: dict) -> str:
    return (
        f"{data['name']} is a {data['type']} located in "
        f"{data['taluka']}, {data['district']} district. It was built by "
        f"{data['built_by']} during the {data['era']} around {data['year_of_construction']}. "
        f"The fort stands at an elevation of about {data['elevation_m']} meters above sea level "
        f"and is currently in a {data['current_condition']} condition. "
        f"Historically, it served as {data['key_events']}. "
        f"The base village for the fort is {data['base_village']}, situated at latitude "
        f"{data['latitude']} and longitude {data['longitude']}. "
        f"The trek to the fort is considered {data['trek_difficulty']} and generally takes "
        f"around {data['trek_time_hours']} hour(s). The best season to visit the fort is during "
        f"{data['best_season']}. Water availability at the fort includes {data['water_availability']}, "
        f"and accommodation options are available in {data['accommodation']}. "
        f"Additional facts: {data['notes']}"
    )

In [13]:
for _, row in df.iterrows():
    # print(row)
    print(fort_dict_to_paragraph(row))
    break

Aad Fort is a Giri Durg (Hill Fort) located in Dapoli, Ratnagiri district. It was built by Unknown during the Maratha Empire around Unknown. The fort stands at an elevation of about 250 meters above sea level and is currently in a In Ruins condition. Historically, it served as Minor watchtower fort. The base village for the fort is Aad, situated at latitude 17.7125 and longitude 73.2391. The trek to the fort is considered Easy and generally takes around 1 hour(s). The best season to visit the fort is during Winter. Water availability at the fort includes nan, and accommodation options are available in nan. Additional facts: A small  lesser-known fort covered in dense vegetation.

In [ ]:
from fastapi.testclient import TestClient
from src.api.main import app

client = TestClient(app=app)


query = input('Ask a question about forts: ')
response = client.get(
    "/search/semantic_search",
    params={"q": f"{query}"}
).json()
print('response:-----')
print(response)

## Option 1 — Import Routers & Call Functions Directly

In [ ]:
from src.core.data_loader import load_forts
from src.api.routers.forts import list_forts, get_fort

In [ ]:
# Test data loading
df = load_forts()
df.head()

In [ ]:
result = list_forts(limit=5, q=None, district=None)
result

In [ ]:
result[0]

In [ ]:
result = list_forts(limit=10, q="shivaji", district=None)
result

In [ ]:
from src.api.routers.clustering import get_clusters, predict_cluster

get_clusters()

In [ ]:
predict_cluster(lat=18.52, lon=73.85)

In [4]:
import os
import torch
from sentence_transformers import SentenceTransformer, util


class RAGEngine:
    def __init__(self, cache_dir="rag_cache"):
        self.df = None
        self.cache_dir = cache_dir

        # Create directory if missing
        os.makedirs(self.cache_dir, exist_ok=True)

        # Cache file paths
        self.corpus_file = os.path.join(cache_dir, "corpus.txt")
        self.emb_file = os.path.join(cache_dir, "embeddings.pt")

        self.corpus = ''
        self.embeddings = None
        self.model = SentenceTransformer("all-MiniLM-L6-v2")

    def fort_dict_to_paragraph(self, data: dict) -> str:
        return (
            f"{data['name']} is a {data['type']} located in "
            f"{data['taluka']}, {data['district']} district. It was built by "
            f"{data['built_by']} during the {data['era']} around {data['year_of_construction']}. "  # NOQA E501
            f"The fort stands at an elevation of about {data['elevation_m']} meters above sea level "  # NOQA E501
            f"and is currently in a {data['current_condition']} condition. "
            f"Historically, it served as {data['key_events']}. "
            f"The base village for the fort is {data['base_village']}, situated at latitude "  # NOQA E501
            f"{data['latitude']} and longitude {data['longitude']}. "
            f"The trek to the fort is considered {data['trek_difficulty']} and generally takes "  # NOQA E501
            f"around {data['trek_time_hours']} hour(s). The best season to visit the fort is during "  # NOQA E501
            f"{data['best_season']}. Water availability at the fort includes {data['water_availability']}, "  # NOQA E501
            f"and accommodation options are available in {data['accommodation']}. "  # NOQA E501
            f"Additional facts: {data['notes']}"
        )

    # -------------------------------------------------------
    # 1. LOAD DATA
    # -------------------------------------------------------
    def build_corpus(self, df):
        if os.path.exists(self.corpus_file):
            print(f"The file '{self.corpus_file}' does not exist.")
            with open(self.corpus_file, 'r') as file:
                self.corpus = file.read()
        else:
            print(f"The file '{self.corpus_file}' does not exist.")
            self.corpus_list = []

            for _, row in df.iterrows():
                self.corpus_list.append(self.fort_dict_to_paragraph(row))

            self.corpus = "\n".join(line.strip() for line in self.corpus_list)

            # Save corpus locally for future reuse
            with open(self.corpus_file, 'w') as file_object:
                file_object.write(self.corpus)

        print(f"RAGEngine: Corpus created with {len(self.corpus)} entries.")
        return self

    # -------------------------------------------------------
    # 2. BUILD OR LOAD INDEX
    # -------------------------------------------------------
    def build_index(self):
        # Try loading cached embeddings
        if os.path.exists(self.emb_file):
            print("RAGEngine: Loading cached embeddings...")
            self.embeddings = torch.load(self.emb_file)
            print("RAGEngine: Embeddings loaded from cache.")
            return self

        # Else build embeddings fresh
        print("RAGEngine: Building new embeddings...")
        self.embeddings = self.model.encode(
            self.corpus,
            convert_to_tensor=True
        )

        # Save embeddings to disk
        torch.save(self.embeddings, self.emb_file)
        print("RAGEngine: Embeddings created and cached.")

        return self

    # -------------------------------------------------------
    # 3. QUERY DOCUMENTS
    # -------------------------------------------------------
    def query(self, user_query, k=5):
        if self.embeddings is None:
            raise ValueError("Index not built. Call build_index().")

        q_emb = self.model.encode(user_query, convert_to_tensor=True)
        scores = util.pytorch_cos_sim(q_emb, self.embeddings)

        # top_idx = torch.topk(scores, k).indices.tolist()

        # Return raw dataframe rows (no formatting)
        # return [self.df.iloc[i].to_dict() for i in top_idx]
        return scores

    # -------------------------------------------------------
    # Extra: force rebuild (if needed)
    # -------------------------------------------------------

    def rebuild_index(self):
        """Manually rebuild all embeddings, ignoring cache."""
        print("RAGEngine: Force rebuilding embeddings...")
        self.embeddings = self.model.encode(
            self.corpus, convert_to_tensor=True
        )
        torch.save(self.embeddings, self.emb_file)
        print("RAGEngine: Rebuild complete.")
        return self

In [5]:
rag = RAGEngine()
rag.build_corpus(df=df)
rag.build_index()

The file 'rag_cache/corpus.txt' does not exist.
RAGEngine: Corpus created with 257467 entries.
RAGEngine: Building new embeddings...
RAGEngine: Embeddings created and cached.

In [24]:
scores = rag.query("sea fort with strong historical importance", k=3)
scores

tensor([[0.4159]])

In [29]:
top_idx = torch.topk(scores, 1).indices.tolist()
top_idx

[[0]]

In [31]:
df.iloc[top_idx[0]]

,fort_id,name,alternate_names,district,taluka,latitude,longitude,base_village,type,elevation_m,...,built_by,year_of_construction,key_events,trek_difficulty,trek_time_hours,best_season,water_availability,accommodation,asi_protected,notes
0,1,Aad Fort,NaN,Ratnagiri,Dapoli,17.7125,73.2391,Aad,Giri Durg (Hill Fort),250,...,Unknown,Unknown,Minor watchtower fort,Easy,1,Winter,NaN,NaN,FALSE,A small lesser-known fort covered in dense ve...

In [ ]:
from src.core.recommender import recommend_by_proximity, recommend_similar

In [ ]:
df0 = recommend_by_proximity(df, lat=18.52, lon=73.85, k=10)
df0

In [ ]:
df2 = recommend_similar(df, fort_id=1, k=5)
df2.head(5)

## Option 2 — Use FastAPI TestClient

In [ ]:
from fastapi.testclient import TestClient
from src.api.main import app

client = TestClient(app=app)

In [ ]:
r = client.get("/forts")
print(r.status_code)
r.json()[:3]

In [ ]:
client.get(f"/forts/{301}").json()

In [ ]:
def fort_dict_to_paragraph(data: dict) -> str:
    return (
        f"{data['name']} (Fort ID {data['fort_id']}) is a {data['type']} located in "
        f"{data['taluka']}, {data['district']} district. It was built by "
        f"{data['built_by']} during the {data['era']} around {data['year_of_construction']}. "
        f"The fort stands at an elevation of about {data['elevation_m']} meters above sea level "
        f"and is currently in a {data['current_condition']} condition. "
        f"Historically, it served as {data['key_events']}. "
        f"The base village for the fort is {data['base_village']}, situated at latitude "
        f"{data['latitude']} and longitude {data['longitude']}. "
        f"The trek to the fort is considered {data['trek_difficulty']} and generally takes "
        f"around {data['trek_time_hours']} hour(s). The best season to visit the fort is during "
        f"{data['best_season']}. Water availability at the fort includes {data['water_availability']}, "
        f"and accommodation options are available in {data['accommodation']}. "
        f"The fort is an ASI-protected site: {data['asi_protected']}. "
        f"Additional notes: {data['notes']}"
    )

In [ ]:
one = ""

In [ ]:
one = " ".join(fort_dict_to_paragraph(data).strip() for data in result)
one

In [ ]:
client.get("/forts", params={"q": "Sindhudurg"}).json()[:3]

In [ ]:
client.get(
    "/search/semantic_search",
    params={"q": "sea forts built by shivaji"}
).json()

In [ ]:
tests = {
    "forts_list": client.get("/forts"),
    "search": client.get("/forts", params={"q":"hill"}),
    "single_fort": client.get("/forts/1"),
    "cluster_summary": client.get("/clusters"),
    "cluster_predict": client.get("/clusters/predict", params={"lat":18.5,"lon":73.8}),
    "nearby": client.get("/recommend/nearby", params={"lat":18.5,"lon":73.8,"k":3}),
    "similar": client.get("/recommend/similar/10", params={"k":3}),
    "rag_search": client.get("/search/semantic_search", params={"q":"sea fort in Sindhudurg district"})
}

for name, result in tests.items():
    print(f"\n--- {name.upper()} ---")
    print("Status:", result.status_code)
    print("Sample:", result.json()[:2] if isinstance(result.json(), list) else result.json())

In [ ]:
import requests
import pandas as pd

BASE = "http://localhost:8000"

def show(x):
    """Pretty print JSON or DataFrame intelligently."""
    if isinstance(x, list):
        if len(x) == 0:
            print("[] (empty list)")
        else:
            display(pd.DataFrame(x).head())
    elif isinstance(x, dict):
        print(x)
    else:
        print(x)

In [ ]:
try:
    r = requests.get(f"{BASE}/forts")
    print("STATUS:", r.status_code)
except Exception as e:
    print("❌ Cannot reach backend:", e)

In [ ]:
forts = requests.get(f"{BASE}/forts").json()
show(forts)

In [ ]:
clusters = requests.get(f"{BASE}/data")
print("Cluster Counts:")
print(clusters)

In [7]:
from fastapi.testclient import TestClient
from src.api.main import app

client = TestClient(app=app)

/home/vasant/projects/Pride-of-Sahyadri/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

RAGEngine: Corpus created with 346 entries.
RAGEngine: Loading cached embeddings...
RAGEngine: Embeddings loaded from cache.

/home/vasant/projects/Pride-of-Sahyadri/.venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [8]:
client.get("/clusters").json()

{'0': 89, '1': 67, '2': 18, '3': 70, '4': 79, '5': 23}

In [9]:
clustered = client.get("/clusters/data").json()

In [10]:
clustered[0]

{'fort_id': 1,
 'name': 'Aad Fort',
 'alternate_names': 'Information Not Available',
 'district': 'Ratnagiri',
 'taluka': 'Dapoli',
 'latitude': 17.7125,
 'longitude': 73.2391,
 'base_village': 'Aad',
 'type': 'Giri Durg (Hill Fort)',
 'elevation_m': 250,
 'current_condition': 'In Ruins',
 'era': 'Maratha Empire',
 'built_by': 'Unknown',
 'year_of_construction': 'Unknown',
 'key_events': 'Minor watchtower fort',
 'trek_difficulty': 'Easy',
 'trek_time_hours': 1.0,
 'best_season': 'Winter',
 'water_availability': 'Information Not Available',
 'accommodation': 'Information Not Available',
 'asi_protected': 'FALSE',
 'notes': 'A small  lesser-known fort covered in dense vegetation.',
 'difficulty_num': 1.0,
 'cluster': 0}

In [11]:
client.get("/recommend/nearby", params={"lat":18.5,"lon":73.8,"k":3}).json()

[{'fort_id': 249,
  'name': 'Pisol Fort',
  'alternate_names': '',
  'district': 'Pune',
  'taluka': 'Haveli',
  'latitude': 18.4231,
  'longitude': 73.8312,
  'base_village': 'Pisol',
  'type': 'Giri Durg (Hill Fort)',
  'elevation_m': 850,
  'current_condition': 'Completely Ruined',
  'era': 'Maratha Empire',
  'built_by': 'Unknown',
  'year_of_construction': 'Unknown',
  'key_events': 'A very small watchtower',
  'trek_difficulty': 'Easy',
  'trek_time_hours': 0.5,
  'best_season': 'Winter',
  'water_availability': 'Information Not Available',
  'accommodation': 'Information Not Available',
  'asi_protected': 'FALSE',
  'notes': 'Only a small plinth and a water cistern remain.',
  'distance_km': 9.127436840115315},
 {'fort_id': 101,
  'name': 'Ghotavade Fort',
  'alternate_names': '',
  'district': 'Pune',
  'taluka': 'Mulshi',
  'latitude': 18.5412,
  'longitude': 73.6815,
  'base_village': 'Ghotavade',
  'type': 'Giri Durg (Hill Fort)',
  'elevation_m': 700,
  'current_condition': 'Completely Ruined',
  'era': 'Maratha Empire',
  'built_by': 'Unknown',
  'year_of_construction': 'Unknown',
  'key_events': 'A small hillock fort',
  'trek_difficulty': 'Easy',
  'trek_time_hours': 0.5,
  'best_season': 'Winter',
  'water_availability': 'Information Not Available',
  'accommodation': 'Information Not Available',
  'asi_protected': 'FALSE',
  'notes': 'Almost no structure remains just a small hill.',
  'distance_km': 13.317517422511981},
 {'fort_id': 302,
  'name': 'Sinhagad',
  'alternate_names': 'Kondhana',
  'district': 'Pune',
  'taluka': 'Haveli',
  'latitude': 18.3663,
  'longitude': 73.7558,
  'base_village': 'Donje',
  'type': 'Giri Durg (Hill Fort)',
  'elevation_m': 1312,
  'current_condition': 'Partially Ruined',
  'era': 'Yadava Dynasty; Maratha Empire',
  'built_by': 'Nag Nayak',
  'year_of_construction': 'c. 13th Century',
  'key_events': 'Battle of Sinhagad, 1670, led by Tanaji Malusare',
  'trek_difficulty': 'Easy',
  'trek_time_hours': 0.5,
  'best_season': 'Monsoon; Winter',
  'water_availability': 'Available seasonally; Bottled water sold',
  'accommodation': 'Information Not Available',
  'asi_protected': 'TRUE',
  'notes': 'Famous for pithla-bhakri stalls; Accessible by road to the top.',
  'distance_km': 15.517836803274896}]

In [12]:
client.get("/recommend/similar/2", params={"k":3}).json()

[{'fort_id': 2,
  'name': 'Achala Fort',
  'alternate_names': '',
  'district': 'Nashik',
  'taluka': 'Satana',
  'latitude': 20.4578,
  'longitude': 74.0536,
  'base_village': 'Pimpalgaon',
  'type': 'Giri Durg (Hill Fort)',
  'elevation_m': 1372,
  'current_condition': 'In Ruins',
  'era': 'Maratha Empire',
  'built_by': 'Shivaji Maharaj',
  'year_of_construction': 'c. 17th Century',
  'key_events': 'Part of Satmala hill range forts; Captured by British in 1818',
  'trek_difficulty': 'Medium',
  'trek_time_hours': 2.0,
  'best_season': 'Winter',
  'water_availability': 'Seasonal',
  'accommodation': 'Information Not Available',
  'asi_protected': 'FALSE',
  'notes': 'Twin fort to Ahivantgad, offers great views of the region.',
  'type_score': 1,
  'elev_diff': 0,
  'score': 1.0},
 {'fort_id': 137,
  'name': 'Kamalgad',
  'alternate_names': '',
  'district': 'Satara',
  'taluka': 'Wai',
  'latitude': 17.895,
  'longitude': 73.785,
  'base_village': 'Tupewadi',
  'type': 'Giri Durg (Hill Fort)',
  'elevation_m': 1375,
  'current_condition': 'In Ruins',
  'era': 'Maratha Empire',
  'built_by': 'Unknown',
  'year_of_construction': 'c. 17th Century',
  'key_events': 'Known for its unique natural rock structure with a hole',
  'trek_difficulty': 'Medium',
  'trek_time_hours': 2.0,
  'best_season': 'Winter',
  'water_availability': 'Seasonal',
  'accommodation': 'Information Not Available',
  'asi_protected': 'FALSE',
  'notes': "A flat-topped fort, also called 'Navra-Navri' Dongar by locals.",
  'type_score': 1,
  'elev_diff': 3,
  'score': 0.997},
 {'fort_id': 9,
  'name': 'Ajoba',
  'alternate_names': 'Ajobagad',
  'district': 'Pune',
  'taluka': 'Junnar',
  'latitude': 19.3308,
  'longitude': 73.6744,
  'base_village': 'Dehene',
  'type': 'Giri Durg (Hill Fort)',
  'elevation_m': 1375,
  'current_condition': 'Pinnacle',
  'era': 'Unknown',
  'built_by': 'Unknown',
  'year_of_construction': 'Ancient',
  'key_events': 'Pilgrimage site for Valmiki Rishi; has a "cradle of Sita" pinnacle',
  'trek_difficulty': 'Hard',
  'trek_time_hours': 4.0,
  'best_season': 'Winter',
  'water_availability': 'Seasonal',
  'accommodation': 'Valmiki Ashram; Caves',
  'asi_protected': 'FALSE',
  'notes': 'Primarily a pilgrimage trek with some fortifications near the top.',
  'type_score': 1,
  'elev_diff': 3,
  'score': 0.997}]

In [13]:
clustered[25]['fort_id']

26

In [14]:
fort_id = clustered[25]['fort_id']  # or if fort_id exists: clustered[0]["fort_id"]

similar = client.get(f"/recommend/similar/{fort_id}", params={"k": 3}).json()

similar

[{'fort_id': 26,
  'name': 'Bahadurgad',
  'alternate_names': '',
  'district': 'Ahilyanagar',
  'taluka': 'Shrigonda',
  'latitude': 18.7831,
  'longitude': 74.6508,
  'base_village': 'Pedgaon',
  'type': 'Bhuikot (Land Fort)',
  'elevation_m': 540,
  'current_condition': 'In Ruins',
  'era': 'Mughal Empire',
  'built_by': 'Aurangzeb',
  'year_of_construction': 'c. 1672',
  'key_events': "Aurangzeb's major Deccan campaign base; renamed Bahadurgad from Pedgaon",
  'trek_difficulty': 'Easy',
  'trek_time_hours': 0.5,
  'best_season': 'Winter',
  'water_availability': 'Information Not Available',
  'accommodation': 'Information Not Available',
  'asi_protected': 'FALSE',
  'notes': 'Known for its Bhuleshwar temple and historical significance during Mughal-Maratha wars.',
  'type_score': 1,
  'elev_diff': 0,
  'score': 1.0},
 {'fort_id': 246,
  'name': 'Piliv Fort',
  'alternate_names': '',
  'district': 'Solapur',
  'taluka': 'Malshiras',
  'latitude': 17.9712,
  'longitude': 74.9513,
  'base_village': 'Piliv',
  'type': 'Bhuikot (Land Fort)',
  'elevation_m': 550,
  'current_condition': 'In Ruins',
  'era': 'Adil Shahi',
  'built_by': 'Unknown',
  'year_of_construction': 'Unknown',
  'key_events': "A land fort or 'gadi' in the village",
  'trek_difficulty': 'Easy',
  'trek_time_hours': 0.2,
  'best_season': 'Winter',
  'water_availability': 'Information Not Available',
  'accommodation': 'Information Not Available',
  'asi_protected': 'FALSE',
  'notes': 'A few walls and a bastion are all that remain.',
  'type_score': 1,
  'elev_diff': 10,
  'score': 0.99},
 {'fort_id': 145,
  'name': 'Karmala Fort',
  'alternate_names': '',
  'district': 'Solapur',
  'taluka': 'Karmala',
  'latitude': 18.4141,
  'longitude': 75.2012,
  'base_village': 'Karmala',
  'type': 'Bhuikot (Land Fort)',
  'elevation_m': 560,
  'current_condition': 'Partially Ruined',
  'era': 'Nizam Shahi',
  'built_by': 'Rao Rambha Nimbalkar',
  'year_of_construction': 'c. 17th Century',
  'key_events': 'A land fort with a large well and a temple',
  'trek_difficulty': 'Easy',
  'trek_time_hours': 0.5,
  'best_season': 'Winter',
  'water_availability': 'Information Not Available',
  'accommodation': 'Information Not Available',
  'asi_protected': 'FALSE',
  'notes': 'The fort is located inside Karmala town.',
  'type_score': 1,
  'elev_diff': 20,
  'score': 0.98}]

In [15]:
client.get("/search/semantic_search", params={"q":"Which forts are difficult treks?"}).json()

{'error': 'selected index k out of range'}

In [4]:
from src.core.cluster_engine import ClusterEngine

cluster_engine = ClusterEngine()
cluster_engine.build_clusters()

(     fort_id                 name            alternate_names     district  \
 0          1             Aad Fort  Information Not Available    Ratnagiri
 1          2          Achala Fort  Information Not Available       Nashik
 2          3        Achalpur Fort             Ellichpur Fort     Amravati
 3          4            Adas Fort  Information Not Available       Satara
 4          5           Ahiwantgad  Information Not Available       Nashik
 ..       ...                  ...                        ...          ...
 341      342         Visapur Fort  Information Not Available         Pune
 342      343            Vishalgad                     Khelna     Kolhapur
 343      344           Worli Fort  Information Not Available  Mumbai City
 344      345  Yashawantgad (Nate)  Information Not Available    Ratnagiri
 345      346          Yashwantgad                  Redi Fort   Sindhudurg

         taluka  latitude  longitude base_village                   type  \
 0       Dapoli   17.7125    73.2391          Aad  Giri Durg (Hill Fort)
 1       Satana   20.4578    74.0536   Pimpalgaon  Giri Durg (Hill Fort)
 2     Achalpur   21.2612    77.5143     Achalpur    Bhuikot (Land Fort)
 3       Khatav   17.6534    74.6543         Adas  Giri Durg (Hill Fort)
 4       Satana   20.4533    74.0494   Pimpalgaon  Giri Durg (Hill Fort)
 ..         ...       ...        ...          ...                    ...
 341      Maval   18.7167    73.4833      Visapur  Giri Durg (Hill Fort)
 342  Shahuwadi   16.8833    73.7833      Gajapur  Giri Durg (Hill Fort)
 343      Worli   19.0167    72.8167        Worli    Jal Durg (Sea Fort)
 344    Rajapur   16.7212    73.3115         Nate    Jal Durg (Sea Fort)
 345   Vengurla   15.7500    73.6667         Redi  Giri Durg (Hill Fort)

      elevation_m  ...                                         key_events  \
 0            250  ...                              Minor watchtower fort
 1           1372  ...  Part of Satmala hill range forts; Captured by ...
 2            358  ...                         Capital of Berar Sultanate
 3            937  ...                              Minor watchtower fort
 4           1385  ...            Treaty of Purandar; Captured by British
 ..           ...  ...                                                ...
 341         1084  ...            Twin fort to Lohagad; built to guard it
 342         1130  ...  Where Shivaji Maharaj escaped to after fleeing...
 343            8  ...  A small watchtower built to keep an eye on ene...
 344           20  ...             A coastal fort guarding the Nate creek
 345           30  ...         A coastal fort guarding the Terekhol creek

     trek_difficulty trek_time_hours      best_season  \
 0              Easy             1.0           Winter
 1            Medium             2.0           Winter
 2              Easy             0.5           Winter
 3              Easy             1.0     Post-Monsoon
 4            Medium             2.0           Winter
 ..              ...             ...              ...
 341            Easy             2.0  Monsoon; Winter
 342            Easy             1.0  Monsoon; Winter
 343            Easy             0.2      All Seasons
 344            Easy             0.5           Winter
 345            Easy             0.5           Winter

             water_availability              accommodation  asi_protected  \
 0    Information Not Available  Information Not Available          FALSE
 1                     Seasonal  Information Not Available          FALSE
 2    Information Not Available  Information Not Available           TRUE
 3    Information Not Available  Information Not Available          FALSE
 4       Year-round in cisterns                      Caves          FALSE
 ..                         ...                        ...            ...
 341                   Seasonal                      Caves          FALSE
 342                  Available            Dargah lodgings          FALSE
 343  Information Not Available  Information Not Available          FALSE
 344  Information Not Available  Information Not Available          FALSE
 345  Information Not Available  Information Not Available          FALSE

                                                  notes difficulty_num cluster
 0    A small  lesser-known fort covered in dense ve...            1.0       0
 1    Twin fort to Ahivantgad, offers great views of...            2.0       1
 2    Located inside the city, known for its massive...            1.0       2
 3         A small fort primarily used as a watch post.            1.0       3
 4    Twin fort to Achala fort, features large caves...            2.0       1
 ..                                                 ...            ...     ...
 341  Known for its huge plateau, numerous water cis...            1.0       4
 342  A large fort with significant historical monum...            1.0       3
 343  Located at the tip of Worli village, offering ...            1.0       0
 344  A different fort from Yashwantgad/Redi Fort in...            1.0       0
 345  Overlooks the beautiful Redi beach and is cove...            1.0       0

 [346 rows x 24 columns],
 {0: 89, 1: 67, 2: 18, 3: 70, 4: 79, 5: 23})

In [5]:
clustered_df = cluster_engine.get_clustered_data()

In [6]:
clustered_df.iloc[0]

fort_id                                                                 1
name                                                             Aad Fort
alternate_names                                 Information Not Available
district                                                        Ratnagiri
taluka                                                             Dapoli
latitude                                                          17.7125
longitude                                                         73.2391
base_village                                                          Aad
type                                                Giri Durg (Hill Fort)
elevation_m                                                           250
current_condition                                                In Ruins
era                                                        Maratha Empire
built_by                                                          Unknown
year_of_construction                                              Unknown
key_events                                          Minor watchtower fort
trek_difficulty                                                      Easy
trek_time_hours                                                       1.0
best_season                                                        Winter
water_availability                              Information Not Available
accommodation                                   Information Not Available
asi_protected                                                       FALSE
notes                   A small  lesser-known fort covered in dense ve...
difficulty_num                                                        1.0
cluster                                                                 0
Name: 0, dtype: object

## RAG Pipeline

### 2. Load Corpus

In [6]:
file_path = "rag_cache/corpus.txt"

with open(file_path, "r", encoding="utf-8") as f:
    text = f.read()

print("Corpus length:", len(text))

Corpus length: 257467

### 3. Chunking (Inspectable)

In [12]:
def chunk_by_sentences(text, chunk_size=5, overlap=2):
    sentences = text.split("\n")
    sentences = [s.strip() for s in sentences if s.strip()]

    chunks = []
    start = 0

    while start < len(sentences):
        end = start + chunk_size
        chunk = " ".join(sentences[start:end])
        chunks.append(chunk)

        start += chunk_size - overlap

    return chunks

chunks = chunk_by_sentences(text)

print("Total chunks:", len(chunks))
print("\nSample chunk:\n", chunks[0])

Total chunks: 116

Sample chunk:
 Aad Fort is a Giri Durg (Hill Fort) located in Dapoli, Ratnagiri district. It was built by Unknown during the Maratha Empire around Unknown. The fort stands at an elevation of about 250 meters above sea level and is currently in a In Ruins condition. Historically, it served as Minor watchtower fort. The base village for the fort is Aad, situated at latitude 17.7125 and longitude 73.2391. The trek to the fort is considered Easy and generally takes around 1 hour(s). The best season to visit the fort is during Winter. Water availability at the fort includes nan, and accommodation options are available in nan. Additional facts: A small  lesser-known fort covered in dense vegetation. Achala Fort is a Giri Durg (Hill Fort) located in Satana, Nashik district. It was built by Shivaji Maharaj during the Maratha Empire around c. 17th Century. The fort stands at an elevation of about 1372 meters above sea level and is currently in a In Ruins condition. Historically, it served as Part of Satmala hill range forts; Captured by British in 1818. The base village for the fort is Pimpalgaon, situated at latitude 20.4578 and longitude 74.0536. The trek to the fort is considered Medium and generally takes around 2 hour(s). The best season to visit the fort is during Winter. Water availability at the fort includes Seasonal, and accommodation options are available in nan. Additional facts: Twin fort to Ahivantgad, offers great views of the region. Achalpur Fort is a Bhuikot (Land Fort) located in Achalpur, Amravati district. It was built by Ahmad Shah Bahmani during the Vatsagulma dynasty; Bahmani Sultanate around c. 1425. The fort stands at an elevation of about 358 meters above sea level and is currently in a In Ruins condition. Historically, it served as Capital of Berar Sultanate. The base village for the fort is Achalpur, situated at latitude 21.2612 and longitude 77.5143. The trek to the fort is considered Easy and generally takes around 0.5 hour(s). The best season to visit the fort is during Winter. Water availability at the fort includes nan, and accommodation options are available in nan. Additional facts: Located inside the city, known for its massive gates and walls. Adas Fort is a Giri Durg (Hill Fort) located in Khatav, Satara district. It was built by Unknown during the Maratha Empire around c. 17th Century. The fort stands at an elevation of about 937 meters above sea level and is currently in a In Ruins condition. Historically, it served as Minor watchtower fort. The base village for the fort is Adas, situated at latitude 17.6534 and longitude 74.6543. The trek to the fort is considered Easy and generally takes around 1 hour(s). The best season to visit the fort is during Post-Monsoon. Water availability at the fort includes nan, and accommodation options are available in nan. Additional facts: A small fort primarily used as a watch post. Ahiwantgad is a Giri Durg (Hill Fort) located in Satana, Nashik district. It was built by Shivaji Maharaj during the Maratha Empire around c. 17th Century. The fort stands at an elevation of about 1385 meters above sea level and is currently in a Partially Ruined condition. Historically, it served as Treaty of Purandar; Captured by British. The base village for the fort is Pimpalgaon, situated at latitude 20.4533 and longitude 74.0494. The trek to the fort is considered Medium and generally takes around 2 hour(s). The best season to visit the fort is during Winter. Water availability at the fort includes Year-round in cisterns, and accommodation options are available in Caves. Additional facts: Twin fort to Achala fort, features large caves and water cisterns.

### 4. Generate Embeddings

In [13]:
from sentence_transformers import SentenceTransformer
from tqdm import tqdm

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(chunks, show_progress_bar=True)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Embedding shape: (116, 384)

### 5. Similarity Function (Core Retrieval Logic)

In [14]:
import numpy as np

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

### 6. Retrieval Function (Debug-Friendly)

In [15]:
def retrieve(query, top_k=3):
    query_vec = model.encode([query])[0]

    scores = [
        cosine_similarity(query_vec, emb)
        for emb in embeddings
    ]

    top_indices = np.argsort(scores)[-top_k:][::-1]

    results = [(chunks[i], scores[i]) for i in top_indices]

    return results

### 7. Test Retrieval (Critical Step)

In [17]:
query = "Tell me about fort Sindhudurg"

results = retrieve(query, top_k=3)

for i, (chunk, score) in enumerate(results):
    print(f"\n--- Result {i+1} | Score: {score:.4f} ---")
    print(chunk[:300])

--- Result 1 | Score: 0.7141 ---
Sindhudurg is a Jal Durg (Sea Fort) located in Malvan, Sindhudurg district. It was built by Shivaji Maharaj during the Maratha Empire around c. 1664. The fort stands at an elevation of about 10 meters above sea level and is currently in a Well-Preserved condition. Historically, it served as Main nav

--- Result 2 | Score: 0.6324 ---
Hanumantgad (Sindhudurg) is a Giri Durg (Hill Fort) located in Dodamarg, Sindhudurg district. It was built by Unknown during the Maratha Empire around Unknown. The fort stands at an elevation of about 350 meters above sea level and is currently in a In Ruins condition. Historically, it served as A f

--- Result 3 | Score: 0.6012 ---
Raikot is a Bhuikot (Land Fort) located in Akole, Ahilyanagar district. It was built by Unknown during the Maratha Empire around Unknown. The fort stands at an elevation of about 750 meters above sea level and is currently in a In Ruins condition. Historically, it served as A small village 'gadi'. T

### 8. Build Context

In [18]:
def build_context(results):
    return "\n\n".join([chunk for chunk, _ in results])

### 9. LLM Generation (Ollama)

In [19]:
import requests

def generate_answer(context, query):
    prompt = f"""
You are a precise assistant. Answer ONLY from the given context.

Context:
{context}

Question:
{query}
"""

    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": "mistral",
            "prompt": prompt,
            "stream": False
        }
    )

    return response.json()["response"]

### 10. Full Pipeline Execution

In [21]:
# query = "Explain the key concept in this document"

results = retrieve(query, top_k=3)
context = build_context(results)

answer = generate_answer(context, query)

print("\nFinal Answer:\n")
print(answer)

KeyboardInterrupt:

### 11. Debug View (Highly Recommended)

In [ ]:
print("==== RETRIEVED CONTEXT ====\n")
print(context)

print("\n==== FINAL ANSWER ====\n")
print(answer)

### 12. Optional: Save Embeddings (Avoid Recompute)

In [ ]:
import numpy as np

np.save("embeddings.npy", embeddings)

In [ ]:
embeddings = np.load("embeddings.npy")